// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	context "context"
	big "math/big"

	mock "github.com/stretchr/testify/mock"

	models "task2/internal/models"
)

// ETHClient is an autogenerated mock type for the ETHClient type
type ETHClient struct {
	mock.Mock
}

// Block provides a mock function with given fields: ctx, num
func (_m *ETHClient) Block(ctx context.Context, num *big.Int) (*models.ETHBlockReduced, error) {
	ret := _m.Called(ctx, num)

	if len(ret) == 0 {
		panic("no return value specified for Block")
	}

	var r0 *models.ETHBlockReduced
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *big.Int) (*models.ETHBlockReduced, error)); ok {
		return rf(ctx, num)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *big.Int) *models.ETHBlockReduced); ok {
		r0 = rf(ctx, num)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ETHBlockReduced)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *big.Int) error); ok {
		r1 = rf(ctx, num)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewETHClient creates a new instance of ETHClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewETHClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ETHClient {
	mock := &ETHClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
